name: UI Web Tests Manual Run
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose Repo Branch:'
        required: true
        default: 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: '17'
    - name: Build & Install
      run: mvn --file pom.xml -B install
    - name: Install Playwright
      run: mvn --file pom.xml exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
    - name: Build with Maven
      run: mvn --file pom.xml -B install -D skipTests
    - name: Run tests in Chrome
      run: mvn -Dtest=testng_regression.xml -DbrowserName=chromium -Dheaded=true test

